// NOTE: auto-generated by tools/version_handler.py, DON'T modify me
namespace HotUpdate {
	export let miniGameVersionInfo = {
    "kgame": {
        "kg1": "0.0.0", 
        "kg2": "0.0.0"
    }, 
    "qqgame": {
        "qq1": "0.1.76", 
        "qq2": "0.1.71", 
        "qq3": "0.1.73"
    }, 
    "ttgame": {
        "tt1": "0.0.0", 
        "tt2": "0.0.0", 
        "tt3": "0.0.0"
    }, 
    "wxgame": {
        "wx1": "0.2.58", 
        "wx2": "0.2.52", 
        "wx3": "0.2.55"
    }
}
}