// NOTE: auto-generated by tools/version_handler.py, DON'T modify me
namespace HotUpdate {
	export let nativeVersionInfo = {
    "banshu": {
        "android": "0.0.1",
        "ios": "0.0.0"
    },
    "chess": {
        "android": "0.0.28",
        "ios": "0.1.16"
    },
    "openew": {
        "android": "0.2.31",
        "ios": "0.7.22",
        "pc": "0.7.30"
    },
    "test": {
        "android": "1.0.95",
        "ios": "0.0.0"
    },
    "xianfeng": {
        "android": "0.0.28",
        "ios": "0.0.1"
    }
}
}
